### ISSUE TITLE
Performing ComBat without standardizing data?

### ISSUE THREAD

**Issue by jakeyeung** [jtleek/sva-devel#20]
Hi, I've been playing around with the sva package with RNA-Seq data and I had a few questions about the `mean.only` and `ref.batch` options in `ComBat()`.

Since in RNA-Seq data, we could report numbers such as fold changes and log counts, I would like my data to still be able to report these types of numbers after `ComBat()`. I was hoping that `mean.only` and `ref.batch` options would allow me to do so. However, the output for `ComBat(mean.only=TRUE, ref.batch=1)` still outputs a matrix that is centered and scaled for every gene.

The line below `cat('Standardizing Data across genes\n')` seems to calculate the maximum likelihood of the parameters, rather than standardizing data (unless I am mistaken?). 

Is it possible to perform `ComBat()` without centering and scaling every gene? 

EDIT: I think there was a bug in my code while I was playing around, I'll close this. Sorry. 

Jake

**Comment by wevanjohnson** [comment]
Jake, 

I’m trying to understand what you mean. Can you send me an example? Maybe with your same experimental design but just a few dozen genes? 

Thanks!

Evan

**Comment by jakeyeung** [comment]
Hi Evan,

Sorry I closed it after I realized that it was probably a bug in my own code. Running `ComBat(mean.only=TRUE, ref.batch=1)` worked for me. 

Sorry for wasting your time. But I didn't know how to delete the issue after I opened it.



Jake
