### ISSUE TITLE
combat-seq input

### ISSUE THREAD

**Issue by saicharanp18** [jtleek/sva-devel#40]
Hi, 
Thanks for the updated combat-seq.
i am trying to use combat-seq on my rnaseq data. Do i need to input raw counts or normalized counts or log transformed counts. because for combat we prefer log transformed counts.

Thanks,
sai

**Comment by zhangyuqing** [comment]
Hi @saicharanp18, 

Please input only raw counts without normalization or log transformation. ComBat-Seq is designed for integer count data, and will provide adjusted data as integer counts. Let me know if you have any questions. 

Yuqing
