### ISSUE TITLE
Can you add the parameter of ref.batch in ComBat-Seq?

### ISSUE THREAD

**Issue by lincj1994** [jtleek/sva-devel#51]
Hi. Can the parameter of ref.batch be used in ComBat-Seq? I think it will be useful to add such a parameter to ComBat-Seq function.
Thanks.

**Comment by lincj1994** [comment]
I have performed batch effect correction for FPKM and count data separately and I found that combat worked well for FPKM data but the ComBat-Seq didnt remove the batch effect for count data.

**Comment by wevanjohnson** [comment]
Unfortunately, we do not have ref option in ComBat seq at this time. We are working on its, but its not ready for release.

**Comment by wevanjohnson** [comment]
Okay, might be best to just use the ComBat on FPKM if it works the best

**Comment by lincj1994** [comment]
Hi. I'm wondering if it is feasible to normalize the count data of the two batches separately first (for example, using DEseq2) and correct the batch effect then using combat.

**Comment by wevanjohnson** [comment]
Seems reasonable, but we have not tested this. Probably worth a try.
