### ISSUE TITLE
Combat returns negative values.

### ISSUE THREAD

**Issue by lincj1994** [jtleek/sva-devel#52]
Hi. I have performed the batch effect correction using combat but it returned negative values for some genes in specific samples. I'm wondering how to deal with it? Replace the negative values with zero OR with the original values before combat?
Btw：
1. Should I log2 transformed the input data (FPKM) before the combat function? OR it doesn't matter whether to log-transform the data or not.
2. If the input data was log transformed (log FPKM), can I exp the data after combat to get a combated FPKM (exp(log2FPKM))? Thanks.

**Comment by KC-Lan** [comment]
Hi, 
For your first question, maybe you can check this:
[**Combat generating negative values, should I log2 transform first?**](https://support.bioconductor.org/p/73266/)

**Comment by wevanjohnson** [comment]
If you are working with RNA-seq data, check out ComBat-Seq:

https://academic.oup.com/nargab/article/2/3/lqaa078/5909519

**Comment by lincj1994** [comment]
Thanks for your reply!
