### ISSUE TITLE
Should Combat be performed if I want to compare a signature score between TCGA RNA-seq and our own RNA-seq data?

### ISSUE THREAD

**Issue by lincj1994** [jtleek/sva-devel#53]
Hi. I want to compare a signature score derived from ssGSEA based on RNA-seq data between TCGA and our own cohort. I'm wondering if the Combat should be performed betwen TCGA RNA-seq and our own RNA-Seq data first?
Thanks.

**Comment by wevanjohnson** [comment]
Yes, probably a very good idea to use ComBat first. 

However, compare the ssGSEA scores on the unadjusted data first to see if the distributions are different.

**Comment by lincj1994** [comment]
Thanks!
